version: "3.8"
services: 
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    depends_on: 
      - db
    environment:  
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    ports:
      - 3000:80
    volumes:
      - .:/var/www
      - ./db/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/php.ini-development:/usr/local/etc/php/php.ini

  db:
    container_name: mariadb
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3309:3306  
    volumes: 
      - ./db/mariadb-data:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080 
